version: '3.8'

services:
  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    ports:
      - "7880:7880"    # HTTP/WebSocket port
      - "7881:7881/udp" # RTC UDP port
      - "7882:7882"    # TURN port
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml
    restart: unless-stopped
    networks:
      - livekit-network

  redis:
    image: redis:alpine
    container_name: livekit-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge
